# fly.toml app configuration file generated for phonebook-v1 on 2023-08-17T08:44:18+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-v1"
primary_region = "syd"

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
